app:
    build: ./server
    ports:
        - "8080:8080"
    volumes:
        - .:/app
    links:
        - redis
appb:
    build: ./server1
    ports:
        - "8081:8081"
    volumes:
        - .:/app
    links:
        - redis
redis:
    image: redis
    command: redis-server --appendonly yes
    volumes:
        - ./data:/data
